"use client";
import {useEffect,useState} from "react";
const platforms={avatar:"Avatar only — avtr_",creator:"All avatars by creator — usr_"};
export default function OptOutDashboard(){
 const [doc,setDoc]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [type,setType]=useState("avatar"),[id,setId]=useState(""),[proof,setProof]=useState("official-profile-marker"),[marker,setMarker]=useState("unlist"),[reason,setReason]=useState("");
 async function load(){try{const r=await fetch("/api/opt-outs",{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.error);setDoc(j)}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function send(data,question){if(question&&!window.confirm(question))return;setBusy(true);setError("");try{const r=await fetch("/api/opt-outs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error);setError(j?.cleanup?`Exclusion saved. Removed ${j.cleanup.liveRemoved} live, ${j.cleanup.quarantineRemoved} quarantined, ${j.cleanup.reviewRemoved} review avatars.`:data.action==="scan"?`Scan finished: ${j.queued} new marker request(s), ${j.held} held for review.`:"Action saved.");await load()}catch(e){setError(`Could not finish: ${e.message}. If an approval was saved before cleanup failed, click Retry cleanup.`)}finally{setBusy(false)}}
 return <main>
  <a href="/">← Admin</a><h1>Avatar Opt-Outs & Creator Privacy</h1>
  <p className="muted">Owner only. Verify a marker on the actual creator profile/avatar before approving. Community-provider text is not proof of ownership. Do not exclude people based on display names.</p>
  <div className="card"><h2>Approve a verified exclusion</h2><p>Check the avatar description for <code>blacklist</code> or <code>unlist</code>, or the creator's own VRChat bio for <code>permanent_unlist</code>. Open the official VRChat page to verify ownership before approving.</p>
  <div className="row"><select value={type} onChange={e=>{setType(e.target.value);setMarker(e.target.value==="creator"?"permanent_unlist":"unlist")}}><option value="avatar">{platforms.avatar}</option><option value="creator">{platforms.creator}</option></select><input value={id} onChange={e=>setId(e.target.value)} placeholder={type==="avatar"?"avtr_...":"usr_..."}/></div>
  <div className="row"><select value={marker} onChange={e=>setMarker(e.target.value)}>{(type==="avatar"?["unlist","blacklist","owner-request"]:["permanent_unlist","owner-request"]).map(x=><option key={x}>{x}</option>)}</select>
  <select value={proof} onChange={e=>setProof(e.target.value)}><option value="official-profile-marker">Verified on official creator profile</option><option value="avatar-description-marker">Verified on official avatar description</option><option value="creator-request-verified">Verified direct creator request</option><option value="owner-verified">Owner-verified evidence</option></select></div>
  <div className="row"><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Brief reason (avoid private personal data)"/><button disabled={busy} onClick={()=>send({action:"approve",id,type,marker,proof,reason},`Confirm you verified control of ${id}, and exclude ${type==="creator"?"all matching creator avatars":"this avatar"}?`)}>Approve exclusion</button></div>
  <small className="muted">Approval saves the blocklist before removing live/quarantine/review entries. If GitHub cleanup errors, retry below. Publishing of VRChat search files follows the GitHub workflow.</small></div>
  <div className="card"><h2>Maintenance</h2><button disabled={busy} onClick={()=>send({action:"cleanup"})}>Retry cleanup of excluded avatars</button> <button disabled={busy} onClick={()=>send({action:"scan"})}>Scan existing live database for markers</button><p className="muted">If the GitHub automatic builder has not been upgraded yet, open Search Export to update the builder script. Existing workflow should rebuild after a live database change.</p></div>
  <div className="card"><h2>Possible opt-out markers requiring verification ({doc?.pending?.length||0})</h2>
  {!doc?.pending?.length?<p className="muted">No new provider marker reports.</p>:doc.pending.slice(0,150).map((a,i)=><div key={`${a.id}:${a.marker}:${i}`} className="avatar"><b>{a.name||a.id}</b><p className="muted">{a.type} • {a.marker} • {a.id}</p><p className="muted">Discovered via {a.source}. Verify against the real VRChat profile/description before approving. {a.marker==="permanent_unlist"&&a.type==="avatar"?"Provider did not supply a verified creator usr_ ID; find that ID before approving any account-wide exclusion.":""}</p><div className="row">{a.type==="avatar"&&<a href={`https://vrchat.com/home/avatar/${encodeURIComponent(a.id)}`} target="_blank" rel="noreferrer">Open avatar page ↗</a>}<button disabled={busy} onClick={()=>{setType(a.type);setId(a.id);setMarker(a.marker);window.scrollTo({top:0,behavior:"smooth"})}}>Review / fill form</button><button className="danger" disabled={busy} onClick={()=>send({action:"dismiss",type:a.type,id:a.id,marker:a.marker},"Dismiss this unverified marker request?")}>Dismiss request</button></div></div>)}
  </div>
  <div className="card"><h2>Active avatar exclusions ({doc?.excludedAvatars?.length||0})</h2>{(doc?.excludedAvatars||[]).map(a=><div className="row" key={a.id}><code>{a.id}</code><span className="muted">{a.marker}</span><button className="danger" disabled={busy} onClick={()=>send({action:"revoke",type:"avatar",id:a.id},"Revoke this exclusion? This does not re-import the avatar.")}>Revoke</button></div>)}</div>
  <div className="card"><h2>Active creator exclusions ({doc?.excludedCreators?.length||0})</h2>{(doc?.excludedCreators||[]).map(a=><div className="row" key={a.id}><code>{a.id}</code><span className="muted">{a.marker}</span><button className="danger" disabled={busy} onClick={()=>send({action:"revoke",type:"creator",id:a.id},"Revoke creator exclusion? This does not re-import avatars.")}>Revoke</button></div>)}</div>
  {error&&<p role="status">{error}</p>}
 </main>
}
